### ISSUE TITLE
Mails keep queued on unexpected errors

### ISSUE THREAD

**Issue by eht16** [pinax/django-mailer#181]
The default error handler (via `MAILER_EMAIL_BACKEND` setting) will log an info message and defer the mail if the error was one of the expected smtplib or socket errors.
This is fine.

On any other errors, the original exception is raised to make the user aware of the error.
Basically this is also fine but unfortunately breaks (probably intentionally) the loop over all queued mails in `engine.send_all()`. This leads to having all other queued mails to be unprocessed once an unexpected error occurs.

We actually experienced such a case recently where our code generated an invalid email which caused a `ValueError` in `django.core.mail.message.sanitize_address` and then all later queued mails were not processed anymore and the queue grew accordingly.

I see that this is basically intended behavior but I wonder if the above mentioned consequences are actually known.

For now, I overridden the default error handler to not raise an exception on unexpected errors but log them with error log level to get noticed but not break the processing of other mails in the queue.

@spookylukey  are you open to PRs changing the current behavior and if so, do you have a preferred way of handling unexpected errors?

**Comment by spookylukey** [comment]
There is a difficulty with knowing what kind of errors can be produced, especially when different backends could all raise different exceptions. Have you looked at https://github.com/pinax/django-mailer/blob/master/docs/usage.rst#error-handling and is it not sufficient for your needs?

If the question is about changing the default behaviour, the answer depends on what changes you are suggesting :-) 

I'm wary of changing behaviour that could cause more breakage in some other way for other users. For example, ignoring more exceptions, such as ignoring `ValueError` by default, which could include almost anything, could result in other undesirable behaviour, like repeatedly trying something (e.g. some external service) which is not going to work, potentially using up money or other resources.

If I was designing from the blank sheet I might do it differently, but there is value in known behaviour at this point.

**Comment by turicas** [comment]
I'm experiencing the same issue in production (django-mailer 2.3.2, Django 4.2.28, Python 3.13.12, PostgreSQL 17.6 and running the worker with `python manage.py runmailer_pg`).

In my case, a spam bot submitted a contact form with HTML tags in the name field (e.g. `<a href="...">spambot</a>`). This value was interpolated into the `from_email` of an `EmailMessage`, which later caused `django.core.mail.message.sanitize_address` to raise a `ValueError` during `email.send()`.

Since `ValueError` is not in the list of exceptions handled by `handle_delivery_exception` (which only catches `smtplib.*` and `socket.error`), the exception propagated up, killed the worker thread in `postgres.py`, and **the entire mail queue stopped being processed** -- silently. The main process kept running and accepting NOTIFY events, but the worker thread was dead. No emails were sent for weeks until I noticed.

The only way to recover was to manually delete the offending message from the database using Django Admin (`/admin/mailer/message/`) and restart the worker. And if there's another malformed message ahead in the queue, the same thing happens again.

Here's the traceback:

```
Exception in thread Thread-1 (worker):
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1044, in _bootstrap_inner
    self.run()
  [...]
  File "/usr/local/lib/python3.13/site-packages/mailer/postgres.py", line 184, in worker
    send_all()
  File "/usr/local/lib/python3.13/site-packages/mailer/engine.py", line 239, in send_all
    connection, action_taken = error_handler(connection, message, err)
  File "/usr/local/lib/python3.13/site-packages/mailer/engine.py", line 146, in handle_delivery_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/mailer/engine.py", line 224, in send_all
    email.send()
  [...]
  File "/usr/local/lib/python3.13/site-packages/django/core/mail/message.py", line 92, in sanitize_address
    raise ValueError(
        'Invalid address; only %s could be parsed from "%s"' % (token, addr)
    )
ValueError: Invalid address; only <redacted> could be parsed from "<redacted>"
```

The README describes django-mailer's value proposition as **robustness** and **correctness**. These are the exact words used to justify why someone should add this dependency to their stack instead of sending emails directly. But the current behavior produces the opposite outcome: a single malformed message -- which the library itself accepted into the queue without validation -- permanently halts all email delivery, with no automatic recovery and no visible indication that something is wrong (unless you're watching the logs).

For comparison, if I were sending emails directly with Django's `send_mail`, a `ValueError` on one email would crash that one HTTP request. With django-mailer in the mix, that same `ValueError` silently kills email delivery for the entire application indefinitely.

## Related issues

- PR #76 (from 2016) proposed a clean solution: separating "retryable" errors (defer) from "non-retryable" errors (log as `RESULT_ERROR`, delete the message, continue processing the queue). That PR was never merged, but the approach seems right: a message that can never be sent should not block the ones behind it.
- Issue #48 reported the same fundamental problem even earlier.

## What I think should change

The current default should be reconsidered. A safe default for a mail queue library would be:

1. On unknown exceptions, log the error, mark the message as failed (not deferred), delete it from the queue, and continue processing. This is what PR #76 proposed.
2. The `worker()` function in `postgres.py` (and `send_loop` in `engine.py`) should wrap `send_all()` in a try/except so that an unhandled exception doesn't kill the loop.
3. Ideally, validate the message before accepting it into the queue (in `DbBackend`), so that obviously malformed messages never enter the queue in the first place.

I understand this is a volunteer-maintained project and I appreciate the work that goes into it. I also understand the `MAILER_ERROR_HANDLER` escape hatch exists. But a default that can silently halt all email delivery for an entire application is a default that will bite many users who trust the library's promise of robustness and never think to configure a custom error handler.

I'm happy to work on a PR if the maintainers are open to it.

**Comment by spookylukey** [comment]
@turicas Thanks for looking at this. I'm definitely open to improvements here.

The only part I have a query about is suggestion 1 - "On unknown exceptions, log the error, mark the message as failed (not deferred), delete it from the queue, and continue processing."

The problem here is that "unknown exceptions", out of the box includes almost anything, including:
- `ValueError` caused by a bad message that we will never actually send, and should be deleted
- temporary network outages or similar, which could appear as almost anything in terms of the exception we actually process (because we can no longer assume an SMTP backend, it is just as likely to be some REST service for example). For these cases, it is also not safe behaviour to delete from the queue and never retry, as this will result in mails being silently dropped because of temporary outages.


Maybe the right way forward is to just break with old behaviour, and change `handle_delivery_exception` so that it never re-raises. I think the safest default behaviour would be to `defer` all messages, whatever the exception.  This is also what https://github.com/pinax/django-mailer/issues/181#issuecomment-2506566305 suggests above.

I can see that the behaviour of "delete from the queue" is also desirable for **some** exceptions, but at the moment I think that should require the dev to write their own `MAILER_ERROR_HANDLER`.

PR #76 is very old, and, like the original django-mailer code, assumes that you will be sending email using SMTP. Under that assumption it's possible to divide errors into known network errors (which should be retried), and others which should not be retried. At this point in time, however, that division is not possible to do in a way that is a safe default.

I'm completely on board with your points 2 and 3, I'm not sure what is involved in 3 though.

Feel free to come back at me with more thoughts though!
