### ISSUE TITLE
can't pickle lock objects

### ISSUE THREAD

**Issue by davidszotten** [pinax/django-mailer#52]
Hi,

As of 93c378e928feef8cf86d1794b0503611ee9dc739, `manage.py send_mail` has started throwing an exception about pickling. It seems that https://github.com/pinax/django-mailer/blob/master/mailer/engine.py#L131 tries to pickle an `email` with a `connection` attached, and when using the django `smtp` email backend, that connection does indeed have a `_lock` attribute.

```
Traceback (most recent call last):
  File "/srv/project/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/environments/project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/srv/environments/project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/environments/project/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/environments/project/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/srv/environments/project/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/srv/environments/project/local/lib/python2.7/site-packages/mailer/management/commands/send_mail.py", line 30, in handle_noargs
    send_all()
  File "/srv/environments/project/local/lib/python2.7/site-packages/mailer/engine.py", line 131, in send_all
    message.email = email  # For the sake of MessageLog
  File "/srv/environments/project/local/lib/python2.7/site-packages/mailer/models.py", line 134, in _set_email
    self.message_data = email_to_db(val)
  File "/srv/environments/project/local/lib/python2.7/site-packages/mailer/models.py", line 81, in email_to_db
    return base64_encode(pickle.dumps(email))
  File "/usr/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/srv/environments/project/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle lock objects
```

**Comment by spookylukey** [comment]
It looks like 93c378e928feef8cf86d1794b0503611ee9dc739 is the culprit, which is very recent and not in any released version. It probably worked before because you were on a previous version - perhaps you are running from master branch?

It looks potentially like an easy fix.

**Comment by davidszotten** [comment]
Hi. yes, i realised and updated my comment the following day. my temporary workaround was to move `message.email = email` (uses a setter triggering the pickle) above setting `email.connection` but i didn't look at wider context

**Comment by spookylukey** [comment]
`message.email = email` does need to be after the `send()` call. I think simply setting 'email.connection = None' should do it.

**Comment by ossanna16** [comment]
Has this issue been resolved?

**Comment by spookylukey** [comment]
Nope, a patch would be accepted

**Comment by ossanna16** [comment]
@davidszotten Would you be interested in sending in a patch for this? :)
