### ISSUE TITLE
send_mail(): LockFailed

### ISSUE THREAD

**Issue by bastbnl** [pinax/django-mailer#80]
Hi,

I offloaded the mail sending proces to a celery task and I ran into LockFailed when running it from a user that is not permitted to write to the current directory:
```
[2016-12-28 14:14:00,091: ERROR/PoolWorker-2] Task app.send_email[bc0a43ba-b2cc-4131-bda2-30722665ee4a] raised unexpected: LockFailed('failed to create /var/www/brownpapersession/demo/brownpapersession/xxxxx-vps-76199700.114845734606605386126845',)
Traceback (most recent call last):
  File "/var/www/brownpapersession/demo/env-brownpapersession/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/brownpapersession/demo/env-brownpapersession/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/brownpapersession/demo/brownpapersession/app/tasks.py", line 526, in send_email
    send_all()
  File "/var/www/brownpapersession/demo/env-brownpapersession/local/lib/python2.7/site-packages/mailer/engine.py", line 123, in send_all
    acquired, lock = acquire_lock()
  File "/var/www/brownpapersession/demo/env-brownpapersession/local/lib/python2.7/site-packages/mailer/engine.py", line 94, in acquire_lock
    lock.acquire(LOCK_WAIT_TIMEOUT)
  File "/var/www/brownpapersession/demo/env-brownpapersession/local/lib/python2.7/site-packages/lockfile/linklockfile.py", line 21, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
LockFailed: failed to create /var/www/brownpapersession/demo/brownpapersession/xxxxx-vps-76199700.114845734606605386126845
```

PR coming up

**Comment by spookylukey** [comment]
Fixed in 5b62f7a78bd0521ff23b9f6bc0a3d452982ca4e9
